<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "femanagerextended"
 *
 * Auto generated by Extension Builder 2013-06-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'hebo_femanager',
    'description' => 'Extend fe_users and femanager with a new field and a new validation',
    'category' => 'plugin',
    'author' => 'Victor Willhuber  ',
    'author_email' => 'victorwillhuber@gmail.com',
    'author_company' => 'Hebotek',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'experimental',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'femanager' => '6.3.0'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
